// <auto-generated />
using System;
using Learning.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Learning.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Learning.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfe1b882-d29e-41b8-a48d-85910c81dbd2"),
                            Category = "Outdoors",
                            City = "Denver",
                            Date = new DateTime(2026, 2, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A scenic hike through the mountains.",
                            Title = "Hiking Trip",
                            Venue = "Rocky Mountain National Park"
                        },
                        new
                        {
                            Id = new Guid("2f780705-48ec-4a85-b532-679bac6730a0"),
                            Category = "Technology",
                            City = "San Francisco",
                            Date = new DateTime(2026, 3, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Annual conference on emerging technologies.",
                            Title = "Tech Conference",
                            Venue = "Moscone Center"
                        },
                        new
                        {
                            Id = new Guid("4a72c39b-f766-4373-9631-46852e2bcb54"),
                            Category = "Music",
                            City = "New Orleans",
                            Date = new DateTime(2026, 4, 5, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Live jazz performance by local artists.",
                            Title = "Jazz Concert",
                            Venue = "French Quarter Theater"
                        },
                        new
                        {
                            Id = new Guid("38dc6d7f-e134-4fa6-a51c-687ff1227979"),
                            Category = "Art",
                            City = "New York",
                            Date = new DateTime(2026, 5, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Modern art exhibition featuring international artists.",
                            Title = "Art Exhibition",
                            Venue = "Metropolitan Museum of Art"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
